# This is the example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (28 is current forge version)

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/TheGreyGhost/MinecraftByExample/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="examplemod" #mandatory

# The version number of the mod - "there's a few well known ${} variables useable here or just hardcode it" (Not well known by me, but hey)
# Digging into the source (StringSubstitutor.class) I think the valid variables are currently (Forge 1.14.4-28.1.0):
# ${global.mcVersion}, ${global.forgeVersion}, {$file.jarVersion}
# {$file.xxxxx} where xxxxx is a property you have defined elsewhere in the mods.toml file using a table named as [properties]  - see https://github.com/toml-lang/toml
version="${file.jarVersion}" # mandatory.  {$file.jarVersion} copies the version number from the manifest specification, which is set in the build.gradle file.

 # A display name for the mod
displayName="Minecraft By Example" #mandatory

# A URL to query for updates for this mod. See the JSON update specification here:  https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#   updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/TheGreyGhost/MinecraftByExample" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="thegreyghostproudlypresents.png" #optional

# A text field displayed in the mod UI
credits="The Forge, MCP, and FML guys, for making it possible" #optional

# A text field displayed in the mod UI
authors="TGG and others" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Minecraft By Example - a collection of simple working examples of the important concepts in Minecraft and Forge.
'''

# The lines below are not used for MBE but maybe you might want them
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
#[[dependencies.examplemod]] #optional
#    # the modid of the dependency
#    modId="forge" #mandatory
#    # Does this dependency have to exist - if not, ordering below must be specified
#    mandatory=true #mandatory
#    # The version range of the dependency
#    versionRange="[28,)" #mandatory
#    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
#    ordering="NONE"
#    # Side this dependency is applied on - BOTH, CLIENT or SERVER
#    side="BOTH"
# Here's another dependency
#[[dependencies.examplemod]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.14.4]"
#    ordering="NONE"
#    side="BOTH"
